---
abstract: "Test current release against CVE's"
name: Test-CVE
version: '0.03'
author:
  - 'H.Merijn Brand <hmbrand@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.70, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.014'
  HTTP::Tiny: '0'
  JSON::MaybeXS: '0'
  Text::Wrap: '0'
  version: '0'
